/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteRouteImport } from './routes/_mainLayout/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainLayoutReportRouteImport } from './routes/_mainLayout/report'
import { Route as MainLayoutLiveMapRouteImport } from './routes/_mainLayout/live-map'
import { Route as AuthLayoutSignupRouteImport } from './routes/_authLayout/signup'
import { Route as AuthLayoutSigninRouteImport } from './routes/_authLayout/signin'

const MainLayoutRouteRoute = MainLayoutRouteRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutReportRoute = MainLayoutReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutLiveMapRoute = MainLayoutLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const AuthLayoutSignupRoute = AuthLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutSigninRoute = AuthLayoutSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof AuthLayoutSigninRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/live-map': typeof MainLayoutLiveMapRoute
  '/report': typeof MainLayoutReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof AuthLayoutSigninRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/live-map': typeof MainLayoutLiveMapRoute
  '/report': typeof MainLayoutReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_mainLayout': typeof MainLayoutRouteRouteWithChildren
  '/_authLayout/signin': typeof AuthLayoutSigninRoute
  '/_authLayout/signup': typeof AuthLayoutSignupRoute
  '/_mainLayout/live-map': typeof MainLayoutLiveMapRoute
  '/_mainLayout/report': typeof MainLayoutReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/signup' | '/live-map' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/live-map' | '/report'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_mainLayout'
    | '/_authLayout/signin'
    | '/_authLayout/signup'
    | '/_mainLayout/live-map'
    | '/_mainLayout/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  MainLayoutRouteRoute: typeof MainLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/report': {
      id: '/_mainLayout/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof MainLayoutReportRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/live-map': {
      id: '/_mainLayout/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof MainLayoutLiveMapRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_authLayout/signup': {
      id: '/_authLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthLayoutSignupRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/signin': {
      id: '/_authLayout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthLayoutSigninRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutSigninRoute: typeof AuthLayoutSigninRoute
  AuthLayoutSignupRoute: typeof AuthLayoutSignupRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutSigninRoute: AuthLayoutSigninRoute,
  AuthLayoutSignupRoute: AuthLayoutSignupRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface MainLayoutRouteRouteChildren {
  MainLayoutLiveMapRoute: typeof MainLayoutLiveMapRoute
  MainLayoutReportRoute: typeof MainLayoutReportRoute
}

const MainLayoutRouteRouteChildren: MainLayoutRouteRouteChildren = {
  MainLayoutLiveMapRoute: MainLayoutLiveMapRoute,
  MainLayoutReportRoute: MainLayoutReportRoute,
}

const MainLayoutRouteRouteWithChildren = MainLayoutRouteRoute._addFileChildren(
  MainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  MainLayoutRouteRoute: MainLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
